name: CI
on: [push, pull_request]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r pc/requirements.txt
      - run: python pc/train_export.py --csv pc/example_data.csv --out pc/_ci_model.json --max_depth 3 --window 4
